name: CICD

on:
  push:
   branches:
     - main
  pull_request:
   branches:
    - main

jobs:
  # Build workflow
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Install dependencies
      run: |
        go version
        go mod download
    - name: Run build
      run: go build .
    - name: Run vet & lint
      run: |
        go vet .
        golint .
        
          